@startuml bulletinboard
package "bulletinboard" {
    interface MixnetBoard
    interface Board
    class CompositeBoard
    class GitBoard
    
    MixnetBoard <|-- CompositeBoard
    Board <-- CompositeBoard 
    Board <|-- GitBoard
}
@enduml