@startuml main_sequence
skinparam responseMessageBelowArrow true
control Driver as driver
queue BulletinBoard as BulletinBoard
participant Crepe as crepe
driver -> BulletinBoard: update
BulletinBoard -> crepe: input predicate
crepe -> Trustee: action predicate
BulletinBoard <-> Trustee: input artifact
Trustee <-> crypto
Trustee -> BulletinBoard: output artifact
@enduml