@startuml main_sequence
skinparam responseMessageBelowArrow true
control Driver as driver
queue MixnetBoard as MixnetBoard
participant Crepe as crepe
driver <-> MixnetBoard: update
driver -> crepe: input predicate
crepe -> Trustee: action predicate
MixnetBoard <-> Trustee: get input artifact
Trustee <-> crypto
Trustee -> MixnetBoard: post artifact
@enduml