@startuml
skinparam linestyle ortho
package "-" as bbp {
    queue "BulletinBoard" as bb
    component "Serde" as serde
    artifact "ByteTree" as bt
    artifact "Artifact" as ar
}

component "DalekSignature" as sig
component "Crepe" as cr
artifact "Statement" as stmt
artifact "InputPredicate" as ip
artifact "Action" as act


rectangle "StatementVerifier" as sv
rectangle "Trustee" as tr


bb <-up-> serde: bytes
serde <-right-> bt: deser
bt <-down-> ar: deser
ar -> stmt
ar <-down-> tr
stmt -> sv
sv -down-> sig
sig -down-> ip: verify
ip -left-> cr
cr -left-> act: inference
act -left-> tr

@enduml